version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./.mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Pokemons
    ports:
      - 27017:27017