GET http://localhost:9001/pokemon/all
content-type: application/json

###

POST http://localhost:9001/pokemon/
content-type: application/json

{
    "name": "Charmander",
    "gender": "Female",
    "type": "Fire",
    "height": 0.5,
    "weight": 55,
    "photo": "https://assets.../004.png"
}

###

PUT http://localhost:9001/pokemon/626efac08ffda2a4a5877e65
content-type: application/json

{
    "name": "Charmeleon",
    "gender": "Female",
    "type": "Fire",
    "height": 0.8,
    "weight": 75,
    "photo": "https://assets.../005.png"
}

###

DELETE  http://localhost:9001/pokemon/626efb1d8b98e892610280f3
content-type: application/json
