GET http://localhost:9001/api/getAllTeams/
content-type: application/json

###

POST http://localhost:9001/api/createTeam/
content-type: application/json

{
    "name": "My Team2",
    "pokemons": [
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        }
    ]
}

###

PUT http://localhost:9001/api/updateTeam/626f1dc8d6fb01b874ff615b
content-type: application/json

{
    "name": "My Team edited",
    "pokemons": [
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        },
        {
            "image": "efds",
            "type1": "fesf",
            "type2": "gewfgs"
        }
    ]
}

###

DELETE  http://localhost:9001/api/deleteTeam/626f1dc8d6fb01b874ff615b
content-type: application/json
